### ISSUE TITLE
PUNCT_TDOT is missing in every charsets

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#10]
No charset has the definition for three-dots punctuation (U+02C6).

**Comment by BenTalagan** [comment]
Thanks, @laicasaane ! I add this to the list of fixes for the next release. Hopefully, it will be somewhere around the end of next week-end.

**Comment by laicasaane** [comment]
Should we address some punctuation that are included in FreeMonoTengwar, Elfica and Eldamar, but not in Annatar and others?

![other punctuations](https://user-images.githubusercontent.com/1594982/26967029-d246da96-4d26-11e7-8b2f-d96b3520c891.png)

P/S: Elfica doesn't have the punctuation in the middle (squared-four-dots?)

**Comment by BenTalagan** [comment]
Good question. My general thought about this is to stay close to what is attested in Tolkien's works atm. Generally speaking, it means that my current reference is now FreeMonoTengwar, because its set has been carefully devised on these cretaria. So these signs should probably be added to all fonts if they are present in FreeMonoTengwar.

But one thing that may be noted is that these 3 signs can be (more or less) approximated to 1 dot+2dots+1dot / 2dots+2dots / 1dot+3dots+1dot , so there's a temporary solution for 'emulating' these signs (and that has been my preferred method in my tengwar modes up until now).

**Comment by laicasaane** [comment]
I've moved the question to new issue for clarification. 😃 https://github.com/BenTalagan/glaemscribe/issues/11

**Comment by BenTalagan** [comment]
Ok, 1.1.4 has arrived. It should address this issue 😃  (I let you check)
