### ISSUE TITLE
[Guni Charsets] DQUOT_OPEN and DQUOT_CLOSE do not correspond to elvish usage

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#21]
In the standard mapping of Tengwar Unicode, DQUOT_OPEN is the higher one, while DQUOT_CLOSE is the lower. This problem appears in all GlaemUnicode fonts.

**Comment by laicasaane** [comment]
My solution is using U+E06A & U+E06B in the charsets instead.

**Comment by BenTalagan** [comment]
This is because most western languages use the low double quote as an opening sign, and the high double quote as a closing sign. Elvish seems to do it the other way.

I chose to use the mapping from the western part of the unicode to mimic the simple quotes (which do not exist in the FTF norm) but accidentally forgot to inverse the names. Using the norm mapping is eventually a good idea (E06A & B), maybe at one stage, renaming these signs to ELVISH_DQUOT could be a good thing too (to avoid mixing latin and elvish stuff).

Anyway, the fonts are ok. Only the charsets just need a patch, I'll do it your way.

**Comment by BenTalagan** [comment]
Ok, this is fixed by 8cd824b7da238e0a871f57d3b8749e6fa9226918. Thanks for noticing!

**Comment by BenTalagan** [comment]
Closed after 1.2.0 release.
