### ISSUE TITLE
Consider reversing sa-rinke and vowel-tehta in Dan Smith style fonts

### ISSUE THREAD

**Issue by pfstrack** [BenTalagan/glaemscribe#36]
You may want to consider reversing the order of sa-rinke and vowel-tehta for Dan Smith fonts. Right now it is:

consonant:sa-rinke:vowel-tehta

That puts the vowel-tehta above the sa-rinke, which looks weird. If you reverse the order you will get a better result:

consonant:vowel-tehta:sa-rinke

I used apsa, otso and tixe to test this (tixe doesn't change).

**Comment by BenTalagan** [comment]
Thanks Paul for the feedback !

Yes, sarinci are indeed a bit of a nightmare to handle, since there are numerous versions used by Tolkien (short, long, in diagonal, attached to the baseline, attached at the top of the lúva, etc, etc), and those old fonts are really lacking the logic that's been thought more carefully by the Free Tengwar Font Project.

The problem lies in the fact that I would like to keep the logical order in the mode's source code for future compatibility : tengwa+short sarince+tehta, since it is the natural way to express it, and all fonts should handle that feature in that precise order (imho). But those old fonts were not making the distinction between short ligated sarinci and long ending sarinci (that could become themselves tehta carriers in some circumstances).

I'll try to find a solution that does not need to change the mode's logic, meaning that the charset files need a new feature for this (so that the swap is performed automagically by glaemscribe). In fact, I'm realizing that the more I work on this engine, the more the charset files (which were just indexes at start) are mimicing exactly what should be done by the font themselves (through font logic like OpenType lookups). 

To resolve all those issues, I've started to work on my own procedural OpenType fonts with my own calligraphy engine but the stage of this project is pretty early for now, and it'll probably take years to achieve. In the meanwhile, we're a bit constrained to use hacks. That's what I'm going to do here.

**Comment by BenTalagan** [comment]
This is now fixed by 1.3.1. :)

**Comment by pfstrack** [comment]
Wow, that was super fast. I will look at the result this weekend. Thanks.

**Comment by BenTalagan** [comment]
Sure ! The version used by eldamo seems quite old, but the update should be straight forward ; the mode file names however have changed, and there's a probably a little bunch of small fixes here and there in the transcription, and in the tehtar placement as well.

**Comment by pfstrack** [comment]
I finally had time to install this in Eldamo and it works great, thanks.

**Comment by BenTalagan** [comment]
Awesome. I'm eager to see the next version !
