### ISSUE TITLE
npm compatibility?

### ISSUE THREAD

**Issue by galadhremmin** [BenTalagan/glaemscribe#4]
Hi!
Thank you for making this great framework! Would you consider creating a package.json file for npm compatibility? It would make it easier for us who use Glaemscribe to stay current.

**Comment by BenTalagan** [comment]
Hi, @galadhremmin ! Since there are almost no dependencies for Glaemscribe, I believe it would be quite easy to create a package for npm. I already do that for rubygems, and have not had any use cases for a npm package yet but there's already a start to everything. I write it down for my next prior todos. By curiosity, have you already been using Glaemscribe within one of your projects?

**Comment by galadhremmin** [comment]
@BenTalagan yes, I use Glaemscribe in the next version of Parf Edhellen (www.elfdict.com). I think it'll be ready for production in a week or two.

**Comment by BenTalagan** [comment]
@galadhremmin : awesome. I've just pushed a front-end npm package, I hope it will fit your expectations :)
