### ISSUE TITLE
Fonts : No XS version of the consonant modification signs (tild+dash) for halla/ara/telco 

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#9]
1. It seems that Halla isn't included in any virtual tehta below, though Telco and Ara are (even Ara cannot hold any tehta below either way).

2. I have another small problem. It turns out that my mode doesn't play well with Tengwar Annatar (and possibly some other fonts). I use the `GEMINATE_SIGN` to represent the `labialization mark`, but the `DASH_INF_S` doesn't appear well on Telco and Halla. I wonder if you can generate an XS size for just Telco and Halla? I know it could be bothersome because you might also have to generate a XS version for other dashes and tildes. If you don't want to make it, I could make it by my own later on.

Currently
![soffice bin_2017-05-29_21-56-16](https://cloud.githubusercontent.com/assets/1594982/26555611/109cc96e-44c0-11e7-9c04-3379dfcc1360.png)

Should be like this
![soffice bin_2017-05-29_21-56-16-modified](https://cloud.githubusercontent.com/assets/1594982/26555619/187ca686-44c0-11e7-98c2-b1eb9eb14fd5.png)

**Comment by BenTalagan** [comment]
1. You're right. Technically speaking, I'm not sure halla could have ever been used to receive any tehta below, but for consistency, it's probably good to have it. Since we're in pure invention with a Vietnamese mode, why not permitting that kind of 'exotic' way of using halla.
2. I'm not sure about the fact that we have any attested example of telco / ara / halla with that kind of consonant modification signs on them (but I would not claim it since the last parma adds a lot of use cases so a check would be required). Nevertheless, all fonts will fail with the problem you're talking about : for managing the virtual chars, I currently use a small script that generate charts that help me to do the right choices, cf [these charts](https://github.com/BenTalagan/glaemscribe/tree/master/bin_dev/virtual_chars_tool). If you have the glaemscrafu fonts installed, you'll see that the problem is common to all fonts (except tengwar mono of course). I don't think fonts were ever designed to manage that specific case (because it only concerns telco/ara/halla). So if we want it, there is no other possibilities than to add it to the fonts.

I'll think about it and keep the problem open for now.

**Comment by laicasaane** [comment]
Yes, what I meant is adding a that new dash into the font. But if we do that, we must add the same size glyphs for other things like `dash above`, `tilde above` and `tilde below` also. And it might be troublesome since we need to keep the consistency between all fonts too.

Well, at the mean time, I'd just have to choose another tehta (currently, `three dots below`) to represent the `labialization mark` instead of the `dash below`. However, I'd placed myself in a tight-end position since I've used the `double dot below` to represent a tone while it's supposed to be a `palatalization mark` originally, which would be somewhat similar. For me, the `single dot below` can be confused with other marks easily. But the `three dots below` would be too heavy for a simple mark (it doesn't look good either).

**Comment by BenTalagan** [comment]
I do agree with you. I think I will end up adding the modified fonts into the git repository. It will be easier for me to track the patches (modification dates, and what's done) and benefit from git features, and maybe provide a central place for font users (and authors!) to follow the issues linked to the fonts.

To summarise, technically speaking we need 4 new characters dash + tilde above and dash + tilde below. Unluckily, Elfica will need to be patched although it had been remaining untouched up until now. :)

I suggest you keep your temporary solution until I find a bit of time to do that work. I'll keep you informed!

**Comment by BenTalagan** [comment]
Ok, 1.1.4 has arrived. It should address this issue 😃  (I let you check).
